type Timezone = {
  name: string;
  value: string;
}

const timezones: Timezone[] = [
  { name: "(UTC-11:00) Midway Island", value: "Pacific/Midway"},
  { name: "(UTC-11:00) Samoa", value: "Pacific/Pago_Pago"},
  { name: "(UTC-10:00) Hawaii", value: "Pacific/Honolulu"},
  { name: "(UTC-09:00) Alaska", value: "America/Anchorage"},
  { name: "(UTC-08:00 Standard) Pacific Time (US & Canada)", value: "America/Los_Angeles"},
  { name: "(UTC-07:00 DST) Pacific Time (US & Canada)", value: "America/Los_Angeles"},
  { name: "(UTC-08:00 Standard) Tijuana", value: "America/Tijuana"},
  { name: "(UTC-07:00 DST) Tijuana", value: "America/Tijuana"},
  { name: "(UTC-07:00) Arizona", value: "America/Phoenix"},
  { name: "(UTC-07:00 Standard) Mountain Time (US & Canada)", value: "America/Denver"},
  { name: "(UTC-06:00 DST) Mountain Time (US & Canada)", value: "America/Denver"},
  { name: "(UTC-07:00) Chihuahua", value: "America/Chihuahua"},
  { name: "(UTC-07:00) Mazatlan", value: "America/Mazatlan"},
  { name: "(UTC-06:00 Standard) Central Time (US & Canada)", value: "America/Chicago"},
  { name: "(UTC-05:00 DST) Central Time (US & Canada)", value: "America/Chicago"},
  { name: "(UTC-06:00) Mexico City", value: "America/Mexico_City"},
  { name: "(UTC-06:00) Monterrey", value: "America/Monterrey"},
  { name: "(UTC-06:00) Saskatchewan", value: "Canada/Saskatchewan"},
  { name: "(UTC-05:00 Standard) New York", value: "America/New_York"},
  { name: "(UTC-04:00 DST) New York", value: "America/New_York"},
  { name: "(UTC-05:00 Standard) Detroit", value: "America/Detroit"},
  { name: "(UTC-04:00 DST) Detroit", value: "America/Detroit"},
  { name: "(UTC-05:00 Standard) Indiana (East)", value: "America/Indiana/Indianapolis"},
  { name: "(UTC-04:00 DST) Indiana (East)", value: "America/Indiana/Indianapolis"},
  { name: "(UTC-05:00 Standard) Louisville", value: "America/Louisville"},
  { name: "(UTC-04:00 DST) Louisville", value: "America/Louisville"},
  { name: "(UTC-05:00) Bogota", value: "America/Bogota"},
  { name: "(UTC-05:00) Lima", value: "America/Lima"},
  { name: "(UTC-04:30) Caracas", value: "America/Caracas"},
  { name: "(UTC-04:00 Standard) Atlantic Time (Canada)", value: "Canada/Atlantic"},
  { name: "(UTC-03:00 DST) Atlantic Time (Canada)", value: "Canada/Atlantic"},
  { name: "(UTC-04:00) La Paz", value: "America/La_Paz"},
  { name: "(UTC-04:00) Santiago", value: "America/Santiago"},
  { name: "(UTC-03:30) Newfoundland", value: "Canada/Newfoundland"},
  { name: "(UTC-03:00 Standard) Buenos Aires", value: "America/Buenos_Aires"},
  { name: "(UTC-02:00 DST) Buenos Aires", value: "America/Buenos_Aires"},
  { name: "(UTC-03:00) Greenland", value: "Greenland"},
  { name: "(UTC-02:00) Stanley", value: "Atlantic/Stanley"},
  { name: "(UTC-01:00) Azores", value: "Atlantic/Azores"},
  { name: "(UTC-01:00) Cape Verde Is.", value: "Atlantic/Cape_Verde"},
  { name: "(UTC) Casablanca", value: "Africa/Casablanca"},
  { name: "(UTC) Dublin", value: "Europe/Dublin"},
  { name: "(UTC) Lisbon", value: "Europe/Lisbon"},
  { name: "(UTC) London", value: "Europe/London"},
  { name: "(UTC) Monrovia", value: "Africa/Monrovia"},
  { name: "(UTC+01:00 Standard) Amsterdam", value: "Europe/Amsterdam"},
  { name: "(UTC+02:00 DST) Amsterdam", value: "Europe/Amsterdam"},
  { name: "(UTC+01:00 Standard) Belgrade", value: "Europe/Belgrade"},
  { name: "(UTC+02:00 DST) Belgrade", value: "Europe/Belgrade"},
  { name: "(UTC+01:00 Standard) Berlin", value: "Europe/Berlin"},
  { name: "(UTC+02:00 DST) Berlin", value: "Europe/Berlin"},
  { name: "(UTC+01:00 Standard) Bratislava", value: "Europe/Bratislava"},
  { name: "(UTC+02:00 DST) Bratislava", value: "Europe/Bratislava"},
  { name: "(UTC+01:00 Standard) Brussels", value: "Europe/Brussels"},
  { name: "(UTC+02:00 DST) Brussels", value: "Europe/Brussels"},
  { name: "(UTC+01:00 Standard) Budapest", value: "Europe/Budapest"},
  { name: "(UTC+02:00 DST) Budapest", value: "Europe/Budapest"},
  { name: "(UTC+01:00 Standard) Copenhagen", value: "Europe/Copenhagen"},
  { name: "(UTC+02:00 DST) Copenhagen", value: "Europe/Copenhagen"},
  { name: "(UTC+01:00 Standard) Ljubljana", value: "Europe/Ljubljana"},
  { name: "(UTC+02:00 DST) Ljubljana", value: "Europe/Ljubljana"},
  { name: "(UTC+01:00 Standard) Madrid", value: "Europe/Madrid"},
  { name: "(UTC+02:00 DST) Madrid", value: "Europe/Madrid"},
  { name: "(UTC+01:00 Standard) Paris", value: "Europe/Paris"},
  { name: "(UTC+02:00 DST) Paris", value: "Europe/Paris"},
  { name: "(UTC+01:00 Standard) Prague", value: "Europe/Prague"},
  { name: "(UTC+02:00 DST) Prague", value: "Europe/Prague"},
  { name: "(UTC+01:00 Standard) Rome", value: "Europe/Rome"},
  { name: "(UTC+02:00 DST) Rome", value: "Europe/Rome"},
  { name: "(UTC+01:00 Standard) Sarajevo", value: "Europe/Sarajevo"},
  { name: "(UTC+02:00 DST) Sarajevo", value: "Europe/Sarajevo"},
  { name: "(UTC+01:00 Standard) Skopje", value: "Europe/Skopje"},
  { name: "(UTC+02:00 DST) Skopje", value: "Europe/Skopje"},
  { name: "(UTC+01:00 Standard) Stockholm", value: "Europe/Stockholm"},
  { name: "(UTC+02:00 DST) Stockholm", value: "Europe/Stockholm"},
  { name: "(UTC+01:00 Standard) Vienna", value: "Europe/Vienna"},
  { name: "(UTC+02:00 DST) Vienna", value: "Europe/Vienna"},
  { name: "(UTC+01:00 Standard) Warsaw", value: "Europe/Warsaw"},
  { name: "(UTC+02:00 DST) Warsaw", value: "Europe/Warsaw"},
  { name: "(UTC+01:00 Standard) Zagreb", value: "Europe/Zagreb"},
  { name: "(UTC+02:00 DST) Zagreb", value: "Europe/Zagreb"},
  { name: "(UTC+02:00 Standard) Athens", value: "Europe/Athens"},
  { name: "(UTC+03:00 DST) Athens", value: "Europe/Athens"},
  { name: "(UTC+02:00 Standard) Bucharest", value: "Europe/Bucharest"},
  { name: "(UTC+03:00 DST) Bucharest", value: "Europe/Bucharest"},
  { name: "(UTC+02:00 Standard) Cairo", value: "Africa/Cairo"},
  { name: "(UTC+02:00) Harare", value: "Africa/Harare"},
  { name: "(UTC+02:00 Standard) Helsinki", value: "Europe/Helsinki"},
  { name: "(UTC+03:00 DST) Helsinki", value: "Europe/Helsinki"},
  { name: "(UTC+02:00 Standard) Istanbul", value: "Europe/Istanbul"},
  { name: "(UTC+03:00 DST) Istanbul", value: "Europe/Istanbul"},
  { name: "(UTC+02:00 Standard) Jerusalem", value: "Asia/Jerusalem"},
  { name: "(UTC+03:00 DST) Jerusalem", value: "Asia/Jerusalem"},
  { name: "(UTC+02:00 Standard) Kyiv", value: "Europe/Kiev"},
  { name: "(UTC+03:00 DST) Kyiv", value: "Europe/Kiev"},
  { name: "(UTC+02:00 Standard) Minsk", value: "Europe/Minsk"},
  { name: "(UTC+03:00 DST) Minsk", value: "Europe/Minsk"},
  { name: "(UTC+02:00 Standard) Riga", value: "Europe/Riga"},
  { name: "(UTC+03:00 DST) Riga", value: "Europe/Riga"},
  { name: "(UTC+02:00 Standard) Sofia", value: "Europe/Sofia"},
  { name: "(UTC+03:00 DST) Sofia", value: "Europe/Sofia"},
  { name: "(UTC+02:00 Standard) Tallinn", value: "Europe/Tallinn"},
  { name: "(UTC+03:00 DST) Tallinn", value: "Europe/Tallinn"},
  { name: "(UTC+02:00 Standard) Vilnius", value: "Europe/Vilnius"},
  { name: "(UTC+03:00 DST) Vilnius", value: "Europe/Vilnius"},
  { name: "(UTC+03:00 Standard) Baghdad", value: "Asia/Baghdad"},
  { name: "(UTC+03:00) Kuwait", value: "Asia/Kuwait"},
  { name: "(UTC+03:00 Standard) Nairobi", value: "Africa/Nairobi"},
  { name: "(UTC+03:00) Riyadh", value: "Asia/Riyadh"},
  { name: "(UTC+03:00 Standard) Moscow", value: "Europe/Moscow"},
  { name: "(UTC+04:00 DST) Moscow", value: "Europe/Moscow"},
  { name: "(UTC+03:30) Tehran", value: "Asia/Tehran"},
  { name: "(UTC+04:00 Standard) Baku", value: "Asia/Baku"},
  { name: "(UTC+05:00 DST) Baku", value: "Asia/Baku"},
  { name: "(UTC+04:00 Standard) Volgograd", value: "Europe/Volgograd"},
  { name: "(UTC+05:00 DST) Volgograd", value: "Europe/Volgograd"},
  { name: "(UTC+04:00 Standard) Muscat", value: "Asia/Muscat"},
  { name: "(UTC+04:00) Tbilisi", value: "Asia/Tbilisi"},
  { name: "(UTC+04:00) Yerevan", value: "Asia/Yerevan"},
  { name: "(UTC+04:30) Kabul", value: "Asia/Kabul"},
  { name: "(UTC+05:00 Standard) Karachi", value: "Asia/Karachi"},
  { name: "(UTC+05:00) Tashkent", value: "Asia/Tashkent"},
  { name: "(UTC+05:30 Standard) Kolkata", value: "Asia/Kolkata"},
  { name: "(UTC+05:30) Kolkata", value: "Asia/Kolkata"},
  { name: "(UTC+05:45 Standard) Kathmandu", value: "Asia/Kathmandu"},
  { name: "(UTC+05:45) Kathmandu", value: "Asia/Kathmandu"},
  { name: "(UTC+06:00 Standard) Ekaterinburg", value: "Asia/Yekaterinburg"},
  { name: "(UTC+07:00 DST) Ekaterinburg", value: "Asia/Yekaterinburg"},
  { name: "(UTC+06:00 Standard) Almaty", value: "Asia/Almaty"},
  { name: "(UTC+06:00) Dhaka", value: "Asia/Dhaka"},
  { name: "(UTC+07:00 Standard) Novosibirsk", value: "Asia/Novosibirsk"},
  { name: "(UTC+08:00 DST) Novosibirsk", value: "Asia/Novosibirsk"},
  { name: "(UTC+07:00 Standard) Bangkok", value: "Asia/Bangkok"},
  { name: "(UTC+07:00) Bangkok", value: "Asia/Bangkok"},
  { name: "(UTC+07:00 Standard) Jakarta", value: "Asia/Jakarta"},
  { name: "(UTC+07:00) Jakarta", value: "Asia/Jakarta"},
  { name: "(UTC+08:00 Standard) Krasnoyarsk", value: "Asia/Krasnoyarsk"},
  { name: "(UTC+09:00 DST) Krasnoyarsk", value: "Asia/Krasnoyarsk"},
  { name: "(UTC+08:00 Standard) Chongqing", value: "Asia/Chongqing"},
  { name: "(UTC+08:00) Chongqing", value: "Asia/Chongqing"},
  { name: "(UTC+08:00 Standard) Hong Kong", value: "Asia/Hong_Kong"},
  { name: "(UTC+08:00) Hong Kong", value: "Asia/Hong_Kong"},
  { name: "(UTC+08:00 Standard) Kuala Lumpur", value: "Asia/Kuala_Lumpur"},
  { name: "(UTC+08:00) Kuala Lumpur", value: "Asia/Kuala_Lumpur"},
  { name: "(UTC+08:00 Standard) Perth", value: "Australia/Perth"},
  { name: "(UTC+08:00) Perth", value: "Australia/Perth"},
  { name: "(UTC+08:00 Standard) Singapore", value: "Asia/Singapore"},
  { name: "(UTC+08:00) Singapore", value: "Asia/Singapore"},
  { name: "(UTC+08:00 Standard) Taipei", value: "Asia/Taipei"},
  { name: "(UTC+08:00) Taipei", value: "Asia/Taipei"},
  { name: "(UTC+08:00 Standard) Ulaan Bataar", value: "Asia/Ulaanbaatar"},
  { name: "(UTC+08:00) Ulaan Bataar", value: "Asia/Ulaanbaatar"},
  { name: "(UTC+08:00 Standard) Urumqi", value: "Asia/Urumqi"},
  { name: "(UTC+08:00) Urumqi", value: "Asia/Urumqi"},
  { name: "(UTC+09:00 Standard) Irkutsk", value: "Asia/Irkutsk"},
  { name: "(UTC+10:00 DST) Irkutsk", value: "Asia/Irkutsk"},
  { name: "(UTC+09:00 Standard) Seoul", value: "Asia/Seoul"},
  { name: "(UTC+09:00) Seoul", value: "Asia/Seoul"},
  { name: "(UTC+09:00 Standard) Tokyo", value: "Asia/Tokyo"},
  { name: "(UTC+09:00) Tokyo", value: "Asia/Tokyo"},
  { name: "(UTC+09:30 Standard) Adelaide", value: "Australia/Adelaide"},
  { name: "(UTC+09:30) Adelaide", value: "Australia/Adelaide"},
  { name: "(UTC+09:30 Standard) Darwin", value: "Australia/Darwin"},
  { name: "(UTC+09:30) Darwin", value: "Australia/Darwin"},
  { name: "(UTC+10:00 Standard) Yakutsk", value: "Asia/Yakutsk"},
  { name: "(UTC+11:00 DST) Yakutsk", value: "Asia/Yakutsk"},
  { name: "(UTC+10:00 Standard) Brisbane", value: "Australia/Brisbane"},
  { name: "(UTC+10:00) Brisbane", value: "Australia/Brisbane"},
  { name: "(UTC+10:00 Standard) Canberra", value: "Australia/Canberra"},
  { name: "(UTC+10:00) Canberra", value: "Australia/Canberra"},
  { name: "(UTC+10:00 Standard) Guam", value: "Pacific/Guam"},
  { name: "(UTC+10:00) Guam", value: "Pacific/Guam"},
  { name: "(UTC+10:00 Standard) Hobart", value: "Australia/Hobart"},
  { name: "(UTC+10:00) Hobart", value: "Australia/Hobart"},
  { name: "(UTC+10:00 Standard) Melbourne", value: "Australia/Melbourne"},
  { name: "(UTC+10:00) Melbourne", value: "Australia/Melbourne"},
  { name: "(UTC+10:00 Standard) Port Moresby", value: "Pacific/Port_Moresby"},
  { name: "(UTC+10:00) Port Moresby", value: "Pacific/Port_Moresby"},
  { name: "(UTC+10:00 Standard) Sydney", value: "Australia/Sydney"},
  { name: "(UTC+10:00) Sydney", value: "Australia/Sydney"},
  { name: "(UTC+11:00 Standard) Vladivostok", value: "Asia/Vladivostok"},
  { name: "(UTC+12:00 DST) Vladivostok", value: "Asia/Vladivostok"},
  { name: "(UTC+12:00 Standard) Magadan", value: "Asia/Magadan"},
  { name: "(UTC+13:00 DST) Magadan", value: "Asia/Magadan"},
  { name: "(UTC+12:00 Standard) Auckland", value: "Pacific/Auckland"},
  { name: "(UTC+13:00 DST) Auckland", value: "Pacific/Auckland"},
  { name: "(UTC+12:00 Standard) Fiji", value: "Pacific/Fiji"},
  { name: "(UTC+13:00 DST) Fiji", value: "Pacific/Fiji"},
];

export default timezones;
